### ISSUE TITLE
Remove customerId from settings

### ISSUE THREAD

**Issue by f2prateek** [AppsFlyerSDK/AppsFlyer-Segment-Integration#1]
https://github.com/AppsFlyerSDK/AppsFlyer-Segment-Integration/blob/master/app/src/main/java/com/segment/analytics/android/integrations/appsflyer/AppsflyerIntegration.java#L45

It should only be set from the identify call (otherwise it will be the same for the entire project and all devices with this app will set the same customerUserId)

**Comment by shachar-af** [comment]
changed it, thanks!
