### ISSUE TITLE
Remove enableLog from settings

### ISSUE THREAD

**Issue by f2prateek** [AppsFlyerSDK/AppsFlyer-Segment-Integration#2]
https://github.com/AppsFlyerSDK/AppsFlyer-Segment-Integration/blob/master/app/src/main/java/com/segment/analytics/android/integrations/appsflyer/AppsflyerIntegration.java#L43

Rather than use it from the settings, you should check the value from `logger.logLevel` and use that. (typically recommended if the logLevel != NONE you should enable logging).

**Comment by shachar-af** [comment]
changed it, thanks!
