### ISSUE TITLE
Testing Install Conversion (deferred DeepLinking) for applications not released in Google Play Store

### ISSUE THREAD

**Issue by dawidgdanski** [AppsFlyerSDK/AppsFlyer-Segment-Integration#3]
Hey there,

I didn't know where to put my question but I see this project presents some integration for Android so decided to post it here. 
I'm using the Android AppsFlyer SDK and I'm particularly interested in Install conversion data (deferred DeepLinking) which my app receives via `AppsFlyerConversionListener.onInstallConversionDataLoaded()`. I expect in the `conversionData` Map to receive a parameter which my app interprets and navigates to the corresponding screen. The problem at this point is, however, that I don't know how I could test the deferred Deep Links for my application which is not released in Google Play Store yet. 

According to your guidelines the install conversion data should contain the query parameters with values from the link which directed user to the Play Store and the user then installed the application. 

How can I test deferred DeepLinks feature before releasing my app to the Google Play?

**Comment by AppsFlyerGit** [comment]
Please contact: support@appsflyer.com

**Comment by akshayy-iprogrammer** [comment]
Hi, I also want solution for same.

**Comment by samoylenkodmitry** [comment]
Hi, same question
